definitions:
  controller.GeocodeRequest:
    type: object
  controller.SearchRequest:
    type: object
info:
  contact: {}
paths:
  /geocode:
    post:
      consumes:
      - application/json
      description: Search for address suggestions by latitude and longitude
      parameters:
      - description: Lat and Lon
        in: body
        name: lat
        required: true
        schema:
          $ref: '#/definitions/controller.GeocodeRequest'
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: API Private token
        in: header
        name: X-Secret
        required: true
        type: string
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal server error
      summary: Search for address suggestions
      tags:
      - addresses
  /search:
    post:
      consumes:
      - application/json
      description: Search for latitude and longitude by address
      parameters:
      - description: Address
        in: body
        name: lat
        required: true
        schema:
          $ref: '#/definitions/controller.SearchRequest'
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: API Private token
        in: header
        name: X-Secret
        required: true
        type: string
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal server error
      summary: Search for address
      tags:
      - addresses
swagger: "2.0"
